# Generated by Django 4.0 on 2022-02-22 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.RemoveField(
            model_name='laborders',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='tutorregister',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='laborders',
            name='submission_date',
            field=models.DateField(default=datetime.date(2022, 2, 22)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='submission_date',
            field=models.DateField(default=datetime.date(2022, 2, 22)),
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
