# Generated by Django 4.0.3 on 2022-03-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='assignment_completed_file',
            field=models.FileField(default='assignmnt', upload_to=''),
            preserve_default=False,
        ),
    ]
