# Generated by Django 4.0 on 2022-02-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorregister',
            name='profile',
            field=models.FileField(default='qwe', upload_to=''),
            preserve_default=False,
        ),
    ]
