# Generated by Django 4.0.3 on 2022-04-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_laborders_assignment_completed_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='assignment_completed_file',
            new_name='completed_assignment',
        ),
    ]
