# Generated by Django 4.0 on 2022-02-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tutorregister_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorregister',
            name='profile',
        ),
        migrations.AlterField(
            model_name='tutorregister',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
