# Generated by Django 4.0 on 2022-02-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_tutorregister_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laborders',
            old_name='report_guidline',
            new_name='report_guideline',
        ),
    ]
