# Generated by Django 4.0 on 2022-02-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_report_guidline_laborders_report_guideline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laborders',
            old_name='report_guideline',
            new_name='report_guidline',
        ),
    ]
