# Generated by Django 4.0 on 2022-01-24 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_laborders_assigned_laborders_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborders',
            name='submission_date',
            field=models.DateField(default=datetime.date(2022, 1, 24)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='submission_date',
            field=models.DateField(default=datetime.date(2022, 1, 24)),
        ),
    ]
