# Generated by Django 4.0 on 2022-02-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_questions_options_alter_questions_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='city',
        ),
    ]
