# Generated by Django 4.0 on 2022-02-19 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_laborders_submission_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.FileField(upload_to='')),
                ('subject', models.CharField(choices=[('Physics', 'Physics'), ('Math', 'Math')], max_length=100)),
                ('tag', models.CharField(choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='laborders',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tutorregister',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='laborders',
            name='submission_date',
            field=models.DateField(default=datetime.date(2022, 2, 19)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='submission_date',
            field=models.DateField(default=datetime.date(2022, 2, 19)),
        ),
    ]
