# Generated by Django 4.0 on 2022-02-21 07:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0006_questions_laborders_order_id_orders_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborders',
            name='submission_date',
            field=models.DateField(default=datetime.date(2022, 2, 21)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='submission_date',
            field=models.DateField(default=datetime.date(2022, 2, 21)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='subject',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Maths', 'Maths'), ('Chemistry', 'Chemistry'), ('Science', 'Science'), ('English', 'English'), ('Accounting', 'Accounting'), ('Economics', 'Economics'), ('Biology', 'Biology'), ('Programming', 'Programming'), ('Essay Writing', 'Essay Writing'), ('Statistics', 'Statistics'), ('Computer Science', 'Computer Science'), ('Nursing', 'Nursing'), ('Case Study Writing', 'Case Study Writing'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Finance', 'Finance'), ('Civil Engineering', 'Civil Engineering')], max_length=100),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('rating', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
