# Generated by Django 4.0 on 2022-02-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='subject',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Maths', 'Maths'), ('Essay Writing', 'Essay Writing'), ('Chemistry', 'Chemistry'), ('Science', 'Science'), ('English', 'English'), ('Accounting', 'Accounting'), ('Economics', 'Economics'), ('Management', 'Management'), ('Biology', 'Biology'), ('Programming', 'Programming'), ('Essay Writing', 'Essay Writing'), ('Chemical Engineering', 'Chemical Engineering'), ('Statistics', 'Statistics'), ('Computer Science', 'Computer Science'), ('Nursing', 'Nursing'), ('Case Study Writing', 'Case Study Writing'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Finance', 'Finance'), ('Civil Engineering', 'Civil Engineering')], max_length=100),
        ),
    ]
