# Generated by Django 4.0 on 2022-02-22 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_laborders_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborders',
            name='submission_date',
            field=models.DateField(default=datetime.date(2022, 2, 22)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='submission_date',
            field=models.DateField(default=datetime.date(2022, 2, 22)),
        ),
    ]
