# Generated by Django 4.0 on 2022-02-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_report_guideline_laborders_report_guidline'),
        ('app', '0009_alter_questions_subject'),
    ]

    operations = [
    ]
