# Generated by Django 4.0 on 2022-02-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_laborders_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Tutor', 'Tutor')], default='Student', max_length=100),
            preserve_default=False,
        ),
    ]
