# Generated by Django 4.0 on 2022-02-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_userdetails_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user_type',
        ),
    ]
