from os import name
from django.urls import path
from app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.home ,name = 'home'),
    path('blog/',views.blog,name='blog'),
    path("blog/top-10-scholarships-for-college-students/", views.blog1, name="blog-1"),
    path("blog/best-tips-and-tricks-to-do-homework-fast/", views.blog2, name="blog-2"),
    path("blog/top-informative-speech-topics/", views.blog3, name="blog-3"),
    path("blog/top-persuasive-speech-topics/", views.blog4, name="blog-4"),
    path("blog/compare-and-contrast-essay-topics/", views.blog5, name="blog-5"),
    path("blog/top-50-research-paper-topics/", views.blog6, name="blog-6"),
    path('online-assignment-help/',views.assignment,name='assignment-help'),
    path('features/',views.features, name='feature'),
    path('reviews/',views.reviews,name='reviews'),
    path('about-us/',views.about,name = 'about-us'),
    path('login/',views.signin,name='login'),
    path('sign-up/',views.signup,name='signup'),
    path('dashboard/old-user',views.dashboard_old,name='old-user'),
    path("dashboard/new_user", views.dashboard_old, name="new-user"),
    path('logout/',views.logout_user,name='logout_user'),
    path('order/',views.onlyorders,name='onlyorders'),
    path('tutor/',views.tutor_login,name='tutor'),
    path('tutor/dashboard/',views.tutor_dashboard,name='tutor-dashboard'),
    path('tutor/register/',views.tutor_register,name='registration'),
    path('essay-writing-services/',views.essay,name='essay'),
    path('live-sessions/',views.live_session,name='live'),
    path('coursework-writing-services/',views.course,name='course-work'),
    path('case-study-writing-services/',views.case,name='case-study'),
    path('dissertation-writing-services/',views.dissert,name='dissertation'),
    path('project-lab-report-help/',views.project,name='project'),
    path('online-homework-help/',views.homework,name='homework'),
    path('chemistry-homework-help/',views.chemistry,name='chemistry'),
    path('physics-homework-help/',views.physics,name='physics'),
    path('math-homework-help/',views.math,name='math'),
    path('science-homework-help/',views.science,name='science'),
    path('english-homework-help/',views.english,name='english'),
    path('programming-homework-help/',views.programming,name='programming'),
    path('biology-homework-help/',views.bio,name='biology'),
    path('engineering-homework-help/',views.engineer,name='engineer'),
    path('computer-science-homework-help/',views.cs,name='cs'),
    path('statistics-homework-help/',views.static_assignment,name='stats'),
    path('accounting-homework-help/',views.accounting,name='accounting'),
    path('economics-homework-help/',views.eco,name='eco'),
    path('nursing-homework-help/',views.nursing,name='nursing'),
    path('management-homework-help/',views.management,name='management'),   
    path('refund-policy/',views.refund,name='refund'),   
    path('privacy-policy/',views.privacy,name='privacy'),   
    path('terms-and-conditions/',views.terms,name='terms'),   
    path('faqs/',views.faq,name='faq'),   
    path("withdrawl/", views.withdrawl_money, name="withdrawl"),
    path('finance-homework-help/',views.finance,name='finance'),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('reset_pass/',views.reset_pass,name='reset_password'),
    path('profile/',views.profile,name='profile'),
    path('live_session_orders/',views.live_session_orders,name='live_session_orders'),
    path('lab_orders/',views.labordes,name='lab_orders'),
    path("tutor_profile/", views.tutor_profile, name="tutor_profile"),
    path('asignment_order/',views.asignment_order,name='asignment_order'),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
