# Generated by Django 2.0.9 on 2022-03-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatter', '0003_auto_20190524_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
    ]
