# Generated by Django 2.2.27 on 2022-03-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatter', '0005_alter_message_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
